export default {
    LOGIN: 'Login',
    TAB_BAR_PROPERTIES: 'Properties',
    TAB_BAR_USERS: 'Surf Leads',
    TAB_BAR_CONTACTS: 'Contacts',
    TAB_BAR_DASHBOARD: 'Dashboard',
    TRANSACTION_DESK: 'Transaction Desk',
    TAB_BAR_MESSAGE: 'surf Mail',
    TAB_BAR_CHAT: 'surf Messaging',
    TAB_BAR_CALL: 'surf Phone',
    AGENTS: "Agents",
    RETALORS: 'Retalors',
    CALL_CENTER: "Call Center",
    USER_PROFILE: 'User Profile',
    CONTACT_VIEW: 'Contact',
    DOCUMENT_PORTAL: 'Document Portal',
    DOCUMENT_PORTAL_DETAIL: 'Document Portal Detail',
    MARKETING: 'Marketing',
    SELF_SOURCED_LEADS: 'Self Sourced Leads',
    MESSAGE_DETAIL: 'Message Detail',
    MAIL_VIEW: 'Mail View',
    KEYPAD: 'Keypad',
    RECENTS: 'Recents',
    SURF_CONTACTS: 'Surf Contacts',
    VOICEMAIL: 'Voicemail',
    SETTING: 'Settings',
    CALENDER_SCREEN: 'Calender',
    NOTIFICATION: 'Notifications',
    PROPERTY_DETAIL: 'Property Detail',
    CREATE_CONTACT: 'Create Contact',
    CONTACT_CARD_START_TRANSACTION: 'Start Transaction',
};